# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-23 04:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datago', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occupation',
            name='category',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='单位性质'),
        ),
        migrations.AlterField(
            model_name='occupation',
            name='industry',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='所属行业'),
        ),
    ]
