# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-28 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datago', '0005_auto_20170825_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='customer_name',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='contract_id',
            field=models.CharField(default='', max_length=40, verbose_name='合同编号'),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='repayment_id',
            field=models.CharField(max_length=60, primary_key=True, serialize=False, verbose_name='还款编号'),
        ),
    ]
