# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 03:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZhbCdProtoinfo',
            fields=[
                ('protoinfo_id', models.CharField(db_column='PROTOINFO_ID', max_length=20, primary_key=True, serialize=False)),
                ('loanid', models.CharField(blank=True, db_column='LOANID', max_length=50, null=True)),
                ('contno', models.CharField(blank=True, db_column='CONTNO', max_length=30, null=True)),
                ('custname', models.CharField(blank=True, db_column='CUSTNAME', max_length=20, null=True)),
                ('paperid', models.CharField(blank=True, db_column='PAPERID', max_length=20, null=True)),
                ('prodid', models.CharField(blank=True, db_column='PRODID', max_length=20, null=True)),
                ('prodname', models.CharField(blank=True, db_column='PRODNAME', max_length=50, null=True)),
                ('tterm', models.CharField(blank=True, db_column='TTERM', max_length=30, null=True)),
                ('tcapi', models.DecimalField(blank=True, db_column='TCAPI', decimal_places=2, max_digits=15, null=True)),
                ('signtotalamt', models.DecimalField(blank=True, db_column='SIGNTOTALAMT', decimal_places=2, max_digits=15, null=True)),
                ('signdate', models.CharField(blank=True, db_column='SIGNDATE', max_length=20, null=True)),
            ],
            options={
                'db_table': 'zhb_cd_protoinfo',
                'managed': False,
            },
        ),
    ]
