# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-24 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('datago', '0003_auto_20170823_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='repay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settle', models.BooleanField(default=False, verbose_name='是否结清')),
                ('preact', models.BooleanField(default=False, verbose_name='是否提前还款')),
                ('repay_overdue', models.BooleanField(default=False, verbose_name='是否有当前逾期')),
                ('repay_overdue_his', models.BooleanField(default=False, verbose_name='是否有历史逾期')),
                ('repay_qici', models.IntegerField(null=True, verbose_name='当期期次')),
                ('yuqi_number', models.IntegerField(null=True, verbose_name='累计逾期期次')),
            ],
        ),
        migrations.RemoveField(
            model_name='contract',
            name='preact',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='repay_overdue',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='repay_overdue_his',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='settle',
        ),
        migrations.AlterField(
            model_name='contract_t',
            name='money_pihe',
            field=models.IntegerField(blank=True, null=True, verbose_name='核批金额'),
        ),
        migrations.AlterField(
            model_name='contract_t',
            name='tuihuiyuanyin',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='退回原因'),
        ),
        migrations.AddField(
            model_name='repay',
            name='contract',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='datago.contract'),
        ),
        migrations.AddField(
            model_name='repay',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='datago.customer'),
        ),
    ]
