# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-12 03:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datago', '0007_auto_20170911_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='repayment',
            name='online',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='线上/线下'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='pos',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='POS机'),
        ),
        migrations.AddField(
            model_name='repayment',
            name='type',
            field=models.CharField(blank=True, default='还款表', max_length=10, verbose_name='表类型'),
        ),
        migrations.AlterField(
            model_name='order_t',
            name='department',
            field=models.CharField(default='', max_length=30, primary_key=True, verbose_name='营业部名称'),
        ),
    ]
