# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 09:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basic',
            fields=[
                ('order_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='订单流水号')),
                ('name', models.CharField(default='', max_length=20, verbose_name='客户姓名')),
                ('IDcard', models.CharField(max_length=19, unique=True, verbose_name='身份证号')),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(default='', max_length=20, verbose_name='发卡行')),
                ('grant_date', models.DateField(blank=True, null=True, verbose_name='发卡日期')),
                ('account_category', models.CharField(default='', max_length=10, verbose_name='账户类别')),
                ('account_state', models.CharField(default='', max_length=10, verbose_name='账户状态')),
                ('query_date', models.DateField(blank=True, null=True, verbose_name='查询年月')),
                ('credit_Line', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='信用额度')),
                ('used_line', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='已使用额度')),
                ('overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('five_years_overdue', models.IntegerField(blank=True, null=True, verbose_name='近五年内逾期月数')),
                ('ninety_days_overdue', models.IntegerField(blank=True, null=True, verbose_name='90天以上逾期次数')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.basic')),
            ],
        ),
        migrations.CreateModel(
            name='chaxun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_date', models.DateField(blank=True, null=True, verbose_name='查询年月')),
                ('c30_person', models.IntegerField(blank=True, null=True, verbose_name='近30天个人查询次数')),
                ('c30_institution_query', models.IntegerField(blank=True, null=True, verbose_name='近30天机构查询次数')),
                ('c30_manage', models.IntegerField(blank=True, null=True, verbose_name='近30天贷后管理次数')),
                ('c60_personal', models.IntegerField(blank=True, null=True, verbose_name='近2个月个人查询次数')),
                ('c60_institution', models.IntegerField(blank=True, null=True, verbose_name='近2个月机构查询次数')),
                ('c60_manage', models.IntegerField(blank=True, null=True, verbose_name='近2个月贷后管理次数')),
                ('c180_personal', models.IntegerField(blank=True, null=True, verbose_name='近6个月个人查询次数')),
                ('c180_institution', models.IntegerField(blank=True, null=True, verbose_name='近6个月机构查询次数')),
                ('c180_manage', models.IntegerField(blank=True, null=True, verbose_name='近6个月贷后管理次数')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.basic')),
            ],
        ),
        migrations.CreateModel(
            name='loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(default='', max_length=20, verbose_name='发放机构')),
                ('grant_date', models.DateField(blank=True, null=True, verbose_name='发卡日期')),
                ('money', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='发放金额')),
                ('account_category', models.CharField(default='', max_length=10, verbose_name='账户类别')),
                ('expired_date', models.DateField(blank=True, null=True, verbose_name='到期日期')),
                ('query_date', models.DateField(blank=True, null=True, verbose_name='查询年月')),
                ('figure', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='余额')),
                ('overdue', models.BooleanField(default=False, verbose_name='是否逾期')),
                ('years5_overdue', models.IntegerField(blank=True, null=True, verbose_name='近五年内逾期月数')),
                ('days90_overdue', models.IntegerField(blank=True, null=True, verbose_name='90天以上逾期次数')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.basic')),
            ],
        ),
    ]
