# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0002_auto_20170928_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='kongbai',
            field=models.BooleanField(default=False, verbose_name='是否征信空白'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='query_date',
            field=models.DateField(null=True, verbose_name='查询年月'),
        ),
    ]
