# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0005_auto_20170928_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='type',
            field=models.CharField(choices=[('简版', '简版征信'), ('详版', '详版征信')], default='jian', max_length=6, verbose_name='征信类型'),
        ),
        migrations.AlterField(
            model_name='card',
            name='account_category',
            field=models.CharField(choices=[('贷记卡', '贷记卡'), ('信用卡', '信用卡'), ('准贷记卡', '准贷记卡')], default='', max_length=10, verbose_name='卡类型'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='type',
            field=models.CharField(choices=[('房贷', '房贷'), ('其他贷款', '其他贷款')], default='---', max_length=10, verbose_name='贷款类型'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='card_notsettled',
            field=models.IntegerField(help_text='仅能填写数字', null=True, verbose_name='信用卡未结清/未销户账户数'),
        ),
    ]
