# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0006_auto_20170928_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='card',
            name='overdue_money',
            field=models.FloatField(null=True, verbose_name='当前逾期金额'),
        ),
        migrations.AddField(
            model_name='loan',
            name='loan_state',
            field=models.CharField(choices=[('持续中', '持续中'), ('已结清', '已结清')], default='持续中', max_length=10, verbose_name='贷款状态'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='IDcard',
            field=models.CharField(default='', editable=False, max_length=19, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='adress',
            field=models.CharField(editable=False, max_length=20, verbose_name='征信影印件'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='kongbai',
            field=models.BooleanField(default=False, verbose_name='征信空白'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='luru',
            field=models.BooleanField(default=False, verbose_name='录入完成'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='name',
            field=models.CharField(default='', editable=False, max_length=10, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='order_id',
            field=models.CharField(editable=False, max_length=30, primary_key=True, serialize=False, verbose_name='订单流水号'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='type',
            field=models.CharField(choices=[('简版', '简版征信'), ('详版', '详版征信')], max_length=6, verbose_name='征信类型'),
        ),
        migrations.AlterField(
            model_name='card',
            name='account_state',
            field=models.CharField(choices=[('正常', '正常'), ('销户', '销户'), ('未激活', '未激活')], max_length=10, verbose_name='账户状态'),
        ),
        migrations.AlterField(
            model_name='card',
            name='credit_Line',
            field=models.FloatField(null=True, verbose_name='信用额度'),
        ),
        migrations.AlterField(
            model_name='card',
            name='overdue',
            field=models.BooleanField(default=False, verbose_name='逾期'),
        ),
        migrations.AlterField(
            model_name='card',
            name='used_line',
            field=models.FloatField(null=True, verbose_name='已使用额度'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='figure',
            field=models.FloatField(null=True, verbose_name='余额'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='money',
            field=models.FloatField(null=True, verbose_name='发放金额'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='overdue',
            field=models.BooleanField(default=False, verbose_name='逾期'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='type',
            field=models.CharField(choices=[('房贷', '房贷'), ('其他贷款', '其他贷款')], max_length=10, verbose_name='贷款类型'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='yuqi_money',
            field=models.FloatField(null=True, verbose_name='逾期金额'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='card_90overdue',
            field=models.IntegerField(help_text='仅限数字', null=True, verbose_name='信用卡发生过90天以上逾期的账户数'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='card_notsettled',
            field=models.IntegerField(help_text='仅限数字', null=True, verbose_name='信用卡未结清/未销户账户数'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='query_date',
            field=models.DateField(null=True, verbose_name='查询日期'),
        ),
    ]
