# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 05:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0008_auto_20170928_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='luresult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('luru', models.BooleanField(default=False, verbose_name='录入完成')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '录入结果',
                'verbose_name_plural': '录入结果',
            },
        ),
        migrations.AlterModelOptions(
            name='basic',
            options={'verbose_name': '客户信息', 'verbose_name_plural': '客户信息'},
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': '信用卡信息', 'verbose_name_plural': '信用卡信息'},
        ),
        migrations.AlterModelOptions(
            name='chaxun',
            options={'verbose_name': '征信查询', 'verbose_name_plural': '征信查询'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': '贷款信息', 'verbose_name_plural': '贷款信息'},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'verbose_name': '信息概要', 'verbose_name_plural': '信息概要'},
        ),
        migrations.RemoveField(
            model_name='basic',
            name='luru',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c_date',
        ),
        migrations.AlterField(
            model_name='basic',
            name='IDcard',
            field=models.CharField(default='', max_length=19, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='adress',
            field=models.CharField(max_length=20, verbose_name='征信影印件'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='name',
            field=models.CharField(default='', max_length=10, verbose_name='客户姓名'),
        ),
        migrations.AlterField(
            model_name='basic',
            name='order_id',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='订单流水号'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='account_category',
            field=models.CharField(default='', max_length=10, verbose_name='贷款用途'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='card_90overdue',
            field=models.IntegerField(null=True, verbose_name='信用卡发生过90天以上逾期的账户数'),
        ),
        migrations.AlterField(
            model_name='summary',
            name='card_notsettled',
            field=models.IntegerField(null=True, verbose_name='信用卡未结清/未销户账户数'),
        ),
    ]
