# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 08:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0011_auto_20170929_1442'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': '信用卡信息（最多添加30条）', 'verbose_name_plural': '信用卡信息（最多添加30条）'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': '贷款信息（最多添加30条）', 'verbose_name_plural': '贷款信息（最多添加30条）'},
        ),
        migrations.RenameField(
            model_name='chaxun',
            old_name='c180_personal',
            new_name='c180_person',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c180_institution',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c180_manage',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c30_institution_query',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c30_manage',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c60_institution',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c60_manage',
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='c60_personal',
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c180_daihou',
            field=models.IntegerField(null=True, verbose_name='近6个月(机构)贷后管理查询次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c180_loan',
            field=models.IntegerField(null=True, verbose_name='近6个月(机构)贷款审批审批次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c180_xyk',
            field=models.IntegerField(null=True, verbose_name='近6个月(机构)信用卡审批次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c30_daihou',
            field=models.IntegerField(null=True, verbose_name='近30天(机构)贷后管理查询次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c30_loan',
            field=models.IntegerField(null=True, verbose_name='近30天(机构)贷款审批审批次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c30_xyk',
            field=models.IntegerField(null=True, verbose_name='近30天(机构)信用卡审批次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c90_daihou',
            field=models.IntegerField(null=True, verbose_name='近3个月(机构)贷后管理查询次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c90_loan',
            field=models.IntegerField(null=True, verbose_name='近3个月(机构)贷款审批审批次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c90_person',
            field=models.IntegerField(null=True, verbose_name='近3个月天个人查询次数'),
        ),
        migrations.AddField(
            model_name='chaxun',
            name='c90_xyk',
            field=models.IntegerField(null=True, verbose_name='近3个月(机构)信用卡审批次数'),
        ),
    ]
