# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0013_auto_20170929_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='order',
        ),
        migrations.DeleteModel(
            name='img',
        ),
    ]
