# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-29 09:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0014_auto_20170929_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='adress',
            field=models.CharField(max_length=150, verbose_name='征信影印件'),
        ),
    ]
