# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 09:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0015_auto_20170929_1722'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': '贷款信息（最多添加30条，不录放款金额在5000元以下的贷款）', 'verbose_name_plural': '贷款信息（最多添加30条，不录放款金额在5000元以下的贷款）'},
        ),
    ]
