# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0016_auto_20170930_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='chaxun1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaxun_date', models.DateField(blank=True, null=True, verbose_name='查询日期')),
                ('caozuoyuan', models.CharField(default='', max_length=50, verbose_name='查询操作员')),
                ('reason', models.CharField(choices=[('贷后管理', '贷后管理'), ('信用卡审批', '信用卡审批'), ('贷款审批', '贷款审批'), ('担保资格审查', '担保资格审查'), ('特约商户实名审查', '特约商户实名审查'), ('其他', '其他')], max_length=20, verbose_name='查询原因')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.basic')),
            ],
            options={
                'verbose_name': '机构征信查询',
                'verbose_name_plural': '机构征信查询',
            },
        ),
        migrations.CreateModel(
            name='chaxun2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chaxun_date', models.DateField(blank=True, null=True, verbose_name='查询日期')),
                ('reason', models.CharField(choices=[('个人临柜查询', '个人临柜查询'), ('个人互联网查询', '个人互联网查询')], max_length=20, verbose_name='查询原因')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.basic')),
            ],
            options={
                'verbose_name': '个人征信查询',
                'verbose_name_plural': '个人征信查询',
            },
        ),
        migrations.RemoveField(
            model_name='chaxun',
            name='order',
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_state',
            field=models.CharField(choices=[('正常', '正常'), ('逾期', '逾期'), ('已结清', '已结清')], max_length=10, verbose_name='贷款状态'),
        ),
        migrations.DeleteModel(
            name='chaxun',
        ),
    ]
