# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 02:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0018_auto_20171019_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='adress',
        ),
        migrations.AlterField(
            model_name='card',
            name='account_state',
            field=models.CharField(choices=[('正常', '正常'), ('销户', '销户'), ('未激活', '未激活'), ('降额', '降额')], max_length=10, verbose_name='账户状态'),
        ),
    ]
