# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0020_auto_20171019_1017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': '贷款信息（最多添加30条，不录放款金额在3000元以下的贷款）', 'verbose_name_plural': '贷款信息（最多添加30条，不录放款金额在3000元以下的贷款）'},
        ),
    ]
