# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-24 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0026_auto_20171020_1111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chaxun1',
            options={'verbose_name': '征信查询-机构(最多添加50条)', 'verbose_name_plural': '征信查询-机构(最多添加50条)'},
        ),
        migrations.AlterModelOptions(
            name='chaxun2',
            options={'verbose_name': '征信查询-个人(最多添加50条)', 'verbose_name_plural': '征信查询-个人(最多添加50条)'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': '贷款信息（最多添加80条）', 'verbose_name_plural': '贷款信息（最多添加80条）'},
        ),
        migrations.AlterField(
            model_name='card',
            name='account_state',
            field=models.CharField(choices=[('正常', '正常'), ('销户', '销户'), ('未激活', '未激活'), ('冻结', '冻结'), ('呆账', '呆账'), ('降额', '降额'), ('止付', '止付'), ('其他', '其他')], max_length=10, verbose_name='账户状态'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='loan_state',
            field=models.CharField(choices=[('正常', '正常'), ('逾期', '逾期'), ('结清', '结清'), ('转出', '转出'), ('呆账', '呆账'), ('其他', '其他')], max_length=10, verbose_name='贷款状态'),
        ),
    ]
