# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 11:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0027_auto_20171024_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='guarantee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_date', models.DateField(null=True, verbose_name='起始日期')),
                ('name_loan', models.CharField(default='', max_length=20, verbose_name='被担保人')),
                ('card_loan', models.CharField(default='', max_length=10, verbose_name='证件号后四位')),
                ('institution', models.CharField(default='', max_length=20, verbose_name='贷款发放机构')),
                ('money', models.FloatField(null=True, verbose_name='担保合同金额')),
                ('money2', models.FloatField(null=True, verbose_name='担保金额')),
                ('query_date', models.DateField(null=True, verbose_name='截止日期')),
                ('figure', models.FloatField(null=True, verbose_name='余额')),
                ('loan_state', models.CharField(choices=[('正常', '正常'), ('逾期', '逾期'), ('结清', '结清'), ('转出', '转出'), ('呆账', '呆账'), ('其他', '其他')], max_length=10, verbose_name='贷款状态')),
                ('yuqi_money', models.FloatField(null=True, verbose_name='逾期金额')),
                ('check_result', models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态')),
            ],
            options={
                'verbose_name': '担保信息',
                'verbose_name_plural': '担保信息',
            },
        ),
        migrations.AlterModelOptions(
            name='card',
            options={'verbose_name': '信用卡信息（最多添加30条, 只录人民币账户）', 'verbose_name_plural': '信用卡信息（最多添加30条, 只录人民币账户）'},
        ),
        migrations.AlterModelOptions(
            name='loan',
            options={'verbose_name': '贷款信息（最多添加80条，不录贷款金额在500元以下贷款）', 'verbose_name_plural': '贷款信息（最多添加80条，不录贷款金额在500元以下贷款）'},
        ),
        migrations.AddField(
            model_name='basic',
            name='check_describe',
            field=models.TextField(blank=True, default='', max_length=200, verbose_name='质检错误描述'),
        ),
        migrations.AddField(
            model_name='basic',
            name='check_num',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='质检出错数目'),
        ),
        migrations.AddField(
            model_name='basic',
            name='check_result',
            field=models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态'),
        ),
        migrations.AddField(
            model_name='basic',
            name='check_user',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='质检员签名'),
        ),
        migrations.AddField(
            model_name='basic',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='check_result',
            field=models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态'),
        ),
        migrations.AddField(
            model_name='chaxun1',
            name='check_result',
            field=models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态'),
        ),
        migrations.AddField(
            model_name='chaxun2',
            name='check_result',
            field=models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态'),
        ),
        migrations.AddField(
            model_name='ggjl',
            name='check_result',
            field=models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态'),
        ),
        migrations.AddField(
            model_name='loan',
            name='check_result',
            field=models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态'),
        ),
        migrations.AddField(
            model_name='summary',
            name='check_result',
            field=models.CharField(blank=True, choices=[('未质检', '未质检'), ('质检合格', '质检合格'), ('质检不合格', '质检不合格'), ('质检中', '质检中')], default='未质检', max_length=20, verbose_name='质检状态'),
        ),
        migrations.AlterField(
            model_name='chaxun1',
            name='reason',
            field=models.CharField(choices=[('贷后管理', '贷后管理'), ('信用卡审批', '信用卡审批'), ('贷款审批', '贷款审批'), ('担保资格审查', '担保资格审查'), ('特约商户实名审查', '特约商户实名审查'), ('保前审查', '保前审查'), ('保后管理', '保后管理'), ('准入资格审查', '准入资格审查'), ('其他', '其他')], max_length=20, verbose_name='查询原因'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='account_category',
            field=models.CharField(choices=[('个人住房贷款', '个人住房贷款'), ('个人公积金住房贷款', '个人公积金住房贷款'), ('个人消费贷款', '个人消费贷款'), ('个人经营贷款', '个人经营贷款'), ('个人信用贷款', '个人信用贷款'), ('农户贷款', '农户贷款'), ('个人汽车贷款', '个人汽车贷款'), ('住房抵押贷款', '住房抵押贷款'), ('汽车抵押贷款', '汽车抵押贷款'), ('抵押担保贷款', '抵押担保贷款'), ('其他抵押贷款', '其他抵押贷款'), ('装修贷款', '装修贷款'), ('助学贷款', '助学贷款'), ('其他贷款', '其他贷款')], default='', max_length=40, verbose_name='贷款用途'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit.basic'),
        ),
    ]
