# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0029_auto_20171103_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='account_category',
            field=models.CharField(default='', max_length=40, verbose_name='贷款用途'),
        ),
    ]
