# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-03 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0031_auto_20171103_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='account_category',
            field=models.CharField(blank=True, default='默认无需填写', help_text='如果贷款用途选了其他贷款，请填写此项，否则无需填写', max_length=40, verbose_name='其他贷款备注'),
        ),
    ]
