# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-16 06:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('credit', '0032_auto_20171103_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chaxun1',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chaxun2',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ggjl',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guarantee',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loan',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='summary',
            name='update_time_ini',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basic',
            name='type',
            field=models.CharField(choices=[('简版', '简版征信'), ('详版', '详版征信')], help_text='如为详版征信，选择详版征信后保存即可，无需录入详细信息', max_length=6, verbose_name='征信类型'),
        ),
        migrations.AlterField(
            model_name='card',
            name='bank',
            field=models.CharField(default='', max_length=80, verbose_name='发卡行'),
        ),
        migrations.AlterField(
            model_name='chaxun1',
            name='reason',
            field=models.CharField(choices=[('贷后管理', '贷后管理'), ('信用卡审批', '信用卡审批'), ('贷款审批', '贷款审批'), ('资信审查', '资信审查'), ('担保资格审查', '担保资格审查'), ('特约商户实名审查', '特约商户实名审查'), ('保前审查', '保前审查'), ('保后管理', '保后管理'), ('准入资格审查', '准入资格审查'), ('公积金提取复核', '公积金提取复核'), ('其他', '其他')], max_length=20, verbose_name='查询原因'),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='institution',
            field=models.CharField(default='', max_length=80, verbose_name='贷款发放机构'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='account_category',
            field=models.CharField(blank=True, default='如前面贷款用途不能涵盖则填写', help_text='如果贷款用途选了其他贷款，请填写此项，否则无需填写', max_length=40, verbose_name='其他贷款备注'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='institution',
            field=models.CharField(default='', max_length=100, verbose_name='发放机构'),
        ),
    ]
