from django.db import models

class department(models.Model):


class 


class credit_evaluation_simple(models.Model):  # 信用评估信息简版
    order_id = models.CharField('订单流水号', max_length=50, primary_key=True)
    name = models.CharField('姓名', max_length=20, default='')
    idcard = models.CharField('身份证号', max_length=19, unique=True)
    credit_card_account = models.IntegerField('信用卡账户数', null=True, blank=True)
    unrepealed_credit_card_account = models.IntegerField('信用卡未销户账户数', null=True, blank=True)
    credit_card_total_line = models.DecimalField('信用卡授信总额', max_digits=12, decimal_places=2, null=True, blank=True)
    credit_card_highest_line = models.DecimalField('信用卡最高授信额', max_digits=12, decimal_places=2, null=True, blank=True)
    credit_card_used_line = models.DecimalField('信用卡已用额度', max_digits=12, decimal_places=2, null=True, blank=True)
    first_credit_card_date = models.DateField('信用卡首卡发放年月', null=True, blank=True)
    credit_card_overdue_money = models.DecimalField('信用卡当前逾期金额', max_digits=12, decimal_places=2, null=True, blank=True)
    credit_card_2years_months = models.IntegerField('两年内发放的信用卡-逾期月数', null=True, blank=True)
    credit_card_90days_months = models.IntegerField('两年内发放的信用卡-90天以上逾期次数', null=True, blank=True)
    housing_loan = models.IntegerField('购房贷款笔数', null=True, blank=True)
    unpaid_housing_loan = models.IntegerField('购房贷款未结清笔数', null=True, blank=True)
    housing_loan_total = models.DecimalField('房贷总额', max_digits=12, decimal_places=2, null=True, blank=True)
    housing_loan_balance = models.DecimalField('房贷余额', max_digits=12, decimal_places=2, null=True, blank=True)
    housing_loan_monthly = models.DecimalField('房贷月还金额', max_digits=12, decimal_places=2, null=True, blank=True)
    first_housing_loan_date = models.DateField('房贷首笔发放年月', null=True, blank=True)
    housing_loan_overdue_money = models.DecimalField('房贷当前逾期金额', max_digits=12, decimal_places=2, null=True, blank=True)
    housing_loan_2years_months = models.IntegerField('两年内发放的房贷-逾期月数', null=True, blank=True)
    housing_loan_90days_months = models.IntegerField('两年内发放的房贷-90天以上逾期次数', null=True, blank=True)
    other_loan = models.IntegerField('其他贷款笔数', null=True, blank=True)
    unpaid_other_loan = models.IntegerField('其他贷款未结清笔数', null=True, blank=True)
    other_loan_monthly = models.DecimalField('其他贷款月还款额', max_digits=12, decimal_places=2, null=True, blank=True)
    other_loan_3month = models.IntegerField('其他贷款近3月内贷款笔数', null=True, blank=True)
    other_loan_overdue_money = models.DecimalField('其他贷款当前逾期金额', max_digits=12, decimal_places=2, null=True, blank=True)
    first_other_loan_date = models.DateField('其他贷款最早发放年月', null=True, blank=True)
    other_loan_2years_months = models.IntegerField('两年内发放的其他贷款-逾期月数', null=True, blank=True)
    other_loan_90days_months = models.IntegerField('两年内发放的其他贷款-90天以上逾期次数', null=True, blank=True)
    one_month_agency_query = models.IntegerField('近一个月内机构查询次数', null=True, blank=True)
    one_month_personal_query = models.IntegerField('近一个月内本人查询次数', null=True, blank=True)
    three_month_personal_query = models.IntegerField('近三个月内查询次数', null=True, blank=True)
    six_month_personal_query = models.IntegerField('近六个月查询次数', null=True, blank=True)
    credit_evaluation_remark = models.CharField('信用评估备注', max_length=400, default='', blank=True)
    update_time = models.DateTimeField('更新时间', auto_now_add=True)

    def __str__(self):
        return self.name


class credit_evaluation_detailed(models.Model):  # 信用评估信息详版
    order_id = models.CharField('订单流水号', max_length=50, primary_key=True)
    name = models.CharField('姓名', max_length=20, default='')
    idcard = models.CharField('身份证号', max_length=19, unique=True)
    housing_loan = models.IntegerField('购房贷款笔数', null=True, blank=True)
    other_loan = models.IntegerField('其他贷款笔数', null=True, blank=True)
    first_loan_date = models.DateField('首贷发放年月', null=True, blank=True)
    credit_card_account = models.IntegerField('信用卡账户数', null=True, blank=True)
    first_credit_card_date = models.DateField('首卡发放年月', null=True, blank=True)
    loan_overdue_months = models.IntegerField('贷款逾期月份数', null=True, blank=True)
    loan_longest_overdue_months = models.IntegerField('贷款最长逾期月数', null=True, blank=True)
    credit_card_overdue_months = models.IntegerField('信用卡逾期月数', null=True, blank=True)
    credit_card_longest_overdue = models.IntegerField('信用卡最长逾期月数', null=True, blank=True)
    unpaid_loan = models.IntegerField('未结清贷款笔数', null=True, blank=True)
    unpaid_loan_total = models.DecimalField('未结清贷款合同总额', max_digits=12, decimal_places=2, null=True, blank=True)
    unpaid_loan_balance = models.DecimalField('未结清贷款余额', max_digits=12, decimal_places=2, null=True, blank=True)
    unpaid_loan_6months = models.DecimalField('未结清贷款最近6个月平均应还额', max_digits=12, decimal_places=2, null=True, blank=True)
    unrepealed_credit_card_account = models.IntegerField('未销户信用卡账户数', null=True, blank=True)
    unrepealed_credit_card_total = models.DecimalField('未销户信用卡授信总额', max_digits=12, decimal_places=2, null=True, blank=True)
    credit_card_highest_line = models.DecimalField('未销户信用卡单家行最高授信额', max_digits=12, decimal_places=2, null=True, blank=True)
    credit_card_used_line = models.DecimalField('未销户信用卡已用额度', max_digits=12, decimal_places=2, null=True, blank=True)
    credit_card_6months_average = models.DecimalField('未销户信用卡最近6个月平均使用额', max_digits=12, decimal_places=2, null=True, blank=True)
    housing_loan_payment = models.IntegerField('购房贷款已结清笔数', null=True, blank=True)
    housing_loan_longest = models.IntegerField('购房贷款最长还款期数', null=True, blank=True)
    housing_loan_total = models.DecimalField('购房贷款房贷总额', max_digits=12, decimal_places=2, null=True, blank=True)
    housing_loan_balance = models.DecimalField('购房贷款房贷余额', max_digits=12, decimal_places=2, null=True, blank=True)
    housing_loan_monthly = models.DecimalField('购房贷款月还金额', max_digits=12, decimal_places=2, null=True, blank=True)
    housing_loan_2years_cumulative = models.IntegerField('购房贷款2年内累计逾期月数', null=True, blank=True)
    housing_loan_2years_longest = models.IntegerField('购房贷款2年内最大连续逾期月数', null=True, blank=True)
    housing_loan_2years_90days = models.IntegerField('购房贷款2年内90天以上逾期次数', null=True, blank=True)
    housing_loan_overdue_money = models.DecimalField('购房贷款当前逾期金额', max_digits=12, decimal_places=2, null=True, blank=True)
    other_loan_2years_cumulative = models.IntegerField('其他贷款2年内累计逾期月数', null=True, blank=True)
    other_loan_2years_longest = models.IntegerField('其他贷款2年内最大连续逾期月数', null=True, blank=True)
    other_loan_2years_90days = models.IntegerField('其他贷款2年内90天以上逾期次数', null=True, blank=True)
    other_loan_overdue_money = models.DecimalField('其他贷款当前逾期金额', max_digits=12, decimal_places=2, null=True, blank=True)
    credit_card_2years_cumulative = models.IntegerField('信用卡2年内累计逾期月数', null=True, blank=True)
    credit_card_2years_longest = models.IntegerField('信用卡2年内最大连续逾期月数', null=True, blank=True)
    credit_card_2years_90days = models.IntegerField('信用卡2年内90天以上逾期次数', null=True, blank=True)
    credit_card__overdue_money = models.DecimalField('信用卡当前逾期金额', max_digits=12, decimal_places=2, null=True, blank=True)
    one_month_agency_query = models.IntegerField('近一个月内机构查询次数', null=True, blank=True)
    one_month_personal_query = models.IntegerField('近一个月内本人查询次数', null=True, blank=True)
    three_month_personal_query = models.IntegerField('近三个月内查询次数', null=True, blank=True)
    six_month_personal_query = models.IntegerField('近六个月查询次数', null=True, blank=True)
    credit_evaluation_remark = models.CharField('信用评估备注', max_length=400, default='', blank=True)
    update_time = models.DateTimeField('更新时间', auto_now_add=True)

    def __str__(self):
        return self.name
